export const FETCH_FLIGHTS_START = "FETCH_FLIGHTS_START";
export const FETCH_FLIGHTS_SUCCESS = "FETCH_FLIGHTS_SUCCESS";
export const FETCH_FLIGHTS_ERROR = "FETCH_FLIGHTS_ERROR";

export const SET_PASSENGERS_COUNT_START = "SET_PASSENGERS_COUNT_START";
export const SET_PASSENGERS_COUNT_SUCCESS = "SET_PASSENGERS_COUNT_SUCCESS";
export const SET_PASSENGERS_COUNT_ERROR = "SET_PASSENGERS_COUNT_ERROR";

export const SET_PRICE_LIMIT_START = "UPDATE_PRICE_LIMIT_START";
export const SET_PRICE_LIMIT_SUCCESS = "SET_PRICE_LIMIT_SUCCESS";
export const SET_PRICE_LIMIT_ERROR = "SET_PRICE_LIMIT_ERROR";

export const SET_ORIGIN_START = "SET_ORIGIN_START";
export const SET_ORIGIN_SUCCESS = "SET_ORIGIN_SUCCESS";
export const SET_ORIGIN_ERROR = "SET_ORIGIN_ERROR";
